### ISSUE TITLE
Error using the contactAPI.get_all_contacts()

### ISSUE THREAD

**Issue by INCM-DSI** [E-goi/sdk-python#2]
Hi,

When getting all the contacts, we are getting the following error:
`Traceback (most recent call last):
  File "C:\...\Python\Python37\lib\site-packages\egoi_api\api_client.py", line 600, in __deserialize_datetime
    return parse(string)
  File "C:\...\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\...\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: year 0 is out of range: 0000-00-00 00:00:00`

I'm using the following code:
`config = egoi_api.Configuration(api_key={"Apikey":"XXX"})
apiClient = egoi_api.ApiClient(configuration=config)
contactAPI = egoi_api.ContactsApi(api_client=apiClient)
thread  = contactAPI.get_all_contacts(newsletterId,async_req=True)
result = thread.get()`

**Comment by renato-gomes** [comment]
Hi,
Please check if Version: 1.1.2RC1 solves your problem.
